### PR TITLE
Add a parameter to choose the OS type

### PR DESCRIPTION
**Pull request by AmineI**
Hi ! I'm back for a last refactoring PR ! 

This one allows to chose the OS type when deploying, between Windows 10 and Windows Server. According to the Azure page, and until @andiradulescu receives an answer from Azure support stating it is false, I've added notes that the Windows 10 deployments requires owning a volume license. 

This can also decouple #39 from the Windows 10 limitation, allowing its awesome changes to get merged without waiting for an answer from Azure support :) 

I also took that opportunity to upgrade Windows Server to 2019. 

__________

- [x] Windows Server 2019 deployments : Tested, and confirmed everything was working, with no behavior or configuration differences between the WS 2016 and WS 2019 deployments. 
- [x] Windows 10 deployments : Tested, and confirmed everything was properly set up.
- [x] Readme updates

__________
[Deployment link for this branch](https://portal.azure.com/#create/Microsoft.Template/uri/https%3A%2F%2Fraw.githubusercontent.com%2FAmineI%2Fazure-gaming%2FOS-parameter%2FStandard.json)

### CODE REVIEW

**Comment by andiradulescu** [comment]
@AmineI - Azure Support replied that it needs an extra 2 to 3 business days to respond. Will ping you when I have an answer from them.

Anyway, nice job with this PR. Thanks!

**Comment by AmineI** [comment]
My pleasure ! I noticed some other interesting OS while browsing the docs : "2019-datacenter-smalldisk". The "smalldisk" variant provisions a ~30GB disk instead of ~128 if I remember correctly. Considering managed disks are billed according to their *sizes* and not *used space*, this could be quite a cost-saving addition for those using the temporary disk with their VMs. Tested that recently and it is working flawlessly. 

On another note, I also finally got around to testing the AMD GPU VMs. For some reason storage performance was really low, but besides that it is working fine with the AMD GPU extension and the setup script. It could be interesting to add that to the template with a conditional deployment for AMD VMs. When I have some time maybe !

**Comment by andiradulescu** [comment]
@AmineI - Interesting. Maybe we could add more variants for the OS.

Regarding AMD GPU VMs, they support Premium SSDs, the disk performance should be way better.

When you have the time, I will be the first to test 🥇 

Regarding Azure Support, they replied, I replied, waiting again.

**Comment by AmineI** [comment]
I think the storage performance issue with AMD GPU VM was because I used a "smalldisk" variant. The disk where Steam was installed was too small for the game I was trying to install (even though I was installing it in the temp disk). Steam probably stores some cache during download on the main disk.

A bullet I noticed in Steam's release notes may have fixed that : 
> Improved updating game content when disk space is low and another Steam library folder on a different disk is available


Any news from Azure support about the licensing debate ? I stated this on the readme and the deployment page

> Note that Windows 10 VMs requires you to own a volume license for it.

so I think it'd be fine to go ahead with that until they answer if it is really needed or not.

**Comment by andiradulescu** [comment]
This was probably the longest support ticket in Azure's history 🥇 

The "final" conclusion:

_The Standard NV6_Promo VM and the Windows 10 Pro 20h1-pro images do not include a license, therefore you would need to have a license to run the Operating System.  I have attached a document that explains various licensing scenarios, which you may find useful in determining which type of license you would like to choose._

And attached this document: https://download.microsoft.com/download/9/8/d/98d6a56c-4d79-40f4-8462-da3ecba2dc2c/licensing_windows_desktop_os_for_virtual_machines.pdf

I tried to figure out what to look for in the document, but I gave up.

So, 👍 for the note regarding Windows 10 VMs require you to own a volume license for it.

**Comment by AmineI** [comment]
Yeah, I'll admit I'm not surprised at the result, but more at the time it took for that support ticket for that licensing info. But hey, I'm sure they had quite a few tickets piled up with COVID and stuff ! Linking the [original license discussion](https://github.com/ecalder6/azure-gaming/pull/39#issuecomment-650782539) for reference

**Comment by AmineI** [comment]
Looks like this was the only blocking point then - only thing left to go is @ecalder6 review, when you can :) !

**Comment by andiradulescu** [comment]
hey @ecalder6 - any chance you might have some time to look over and merge this? thanks!

**Comment by ecalder6** [comment]
Yeah sorry for the delay. Looks good!

**Pull request merged**
